"""empty message

Revision ID: 498efde70acc
Revises: a1e651d7465f
Create Date: 2026-07-09 08:51:51.392827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498efde70acc'
down_revision: Union[str, Sequence[str], None] = 'a1e651d7465f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    user_role = sa.Enum('USER', 'ADMIN', name='userrole')
    user_role.create(op.get_bind())

    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role DROP DEFAULT;
    """)

    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role
        TYPE userrole
        USING role::userrole;
    """)

    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role
        SET DEFAULT 'USER';
    """)

    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###
